repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=2048']
    -   id: check-yaml
        exclude: ^templates/.*$
    -   id: check-toml
        exclude: ^templates/.*$
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: debug-statements
        exclude: ^templates/.*$
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        args: ["--fix"]
        exclude: ^templates/.*$
    -   id: ruff-format
        exclude: ^templates/.*$
