[tool.ruff]
line-length = 120
target-version = "py39"  # Using py39 since that's our current environment
select = ["ALL"]
ignore = ["D100", "D103", "D104", "INP001", "T201"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S101"]  # Allow assert statements in test files

[tool.ruff.pydocstyle]
convention = "google"

[tool.coverage.run]
include = ["src/*"]
omit = ["tests/*"]