site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.description }}
site_author: {{ cookiecutter.author_name }}

repo_url: https://github.com/username/{{ cookiecutter.repo_name }}

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

nav:
  - Home: index.md
  - API Reference: api.md
  - Contributing: contributing.md
