_target_: {{cookiecutter.repo_name}}.models.flow_matching.FlowMatching

model: 
  _target_: {{cookiecutter.repo_name}}.networks.unet.UNet
  in_channels: 1
  out_channels: 1
  model_channels: 64
  time_dim: 256
  num_classes: 10

alpha_beta_scheduler:
  _target_: {{cookiecutter.repo_name}}.modules.schedulers.LinearScheduler
  data_dim: 4

sampler:
  _target_: {{cookiecutter.repo_name}}.modules.samplers.GaussianSampler
  target_shape: [1, 28, 28]

ode_solver:
  _target_: {{cookiecutter.repo_name}}.modules.solvers.EulerSolver

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0